Import('env')
Import('parallel_run')
Import('serial_run')
Import('ip_charm')

Import('bin_path')
Import('test_path')
Import('prec')

#import os
#----------------------------------------------------------
#defines
#----------------------------------------------------------

env['CPIN'] = 'touch parameters.out; mv parameters.out ${TARGET}.in'
env['RMIN'] = 'rm -f parameters.out'
env['clocal_cmd'] = '++local'

#charm_args = os.getenv('CHARM_ARGS','')

date_cmd = 'echo $TARGET > test/STATUS; echo "---------------------"; date +"%Y-%m-%d %H:%M:%S";'

make_movie = Builder(action = "png2swf -r 5 -o $TARGET ${ARGS} ")
png_to_gif = Builder(action = "convert -delay 5 -loop 0 ${ARGS} $TARGET ")

env.Append(BUILDERS = { 'MakeMovie' : make_movie})
env.Append(BUILDERS = { 'pngToGif'  : png_to_gif})


print("Precision:", prec)

run_ppm1 = Builder(action = "$RMIN; " + date_cmd + serial_run + " $SOURCE $ARGS > $TARGET 2>&1; $CPIN; $COPY")
env.Append(BUILDERS = { 'RunPpm1' : run_ppm1 } )
env_mv_ppm1 = env.Clone(COPY = 'mkdir -p ' + test_path + '/MethodFluxCorrect/Inclined-Contact-SMR-Ppm; mv `ls *.png *.h5` ' + test_path + '/MethodFluxCorrect/Inclined-Contact-SMR-Ppm')

#-------------------------------------------------------------
#load balancing
#-------------------------------------------------------------

#serial
if prec == 'double':
   balance_ppm_1 = env_mv_ppm1.RunSerial (
        'inclined_contact_smr_ppm.unit',
        bin_path + '/enzo-e',
        ARGS='input/FluxCorrect/inclined_contact_smr_ppm-double.in')
else:
   balance_ppm_1 = env_mv_ppm1.RunSerial (
        'inclined_contact_smr_ppm.unit',
        bin_path + '/enzo-e',
        ARGS='input/FluxCorrect/inclined_contact_smr_ppm-single.in')

Clean(balance_ppm_1,
     [Glob('#/' + test_path + '/Inclined-Contact-SMR-Ppm*.png'),
      Glob('#/' + test_path + '/Inclined-Contact-SMR-Ppm*.h5')])