#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import('type')

#------------------------------
# DEPENDENCIES
#------------------------------

#------------------------------
# ENVIRONMENTS
#------------------------------

#------------------------------
# SOURCE
#------------------------------

includes = [Glob('*hpp')]

#------------------------------
# TARGETS
#------------------------------

if (type == "charm"):
    env.CharmBuilder('main.decl.h','main.ci',ARG = 'main')
    env.CharmBuilder('main.def.h','main.ci',ARG = 'main')
    includes = includes + ['main.decl.h','main.def.h'] 

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-inc',env.Install ('#/include',includes))




