#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import('type')

Import('bin_path')
Import('inc_path')
Import('lib_path')

#------------------------------
# DEPENDENCIES
#------------------------------

libraries = []
components = []

#------------------------------
# SOURCE
#------------------------------

includes = [Glob('*hpp')]
sources  = [Glob('test*cpp')]

#------------------------------
# ENVIRONMENTS
#------------------------------

env = env.Clone(LIBS=[components,libraries])

#------------------------------
# TARGETS
#------------------------------

libraries  = env.Library ('test', [sources])

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-inc',env.Install (inc_path,includes))
env.Alias('install-lib',env.Install (lib_path,libraries))





