#!/bin/csh -f

rm *.hdf5 *.png

test_parallel_jacobi 16 8 2

set s = 1
foreach f (*hdf5)
   set i = 0
   while ($i < 10)
      h5topng -m 0 -M 1 -x $i -S $s $f
      mv $f.png $f:r-p8-x$i.$f:e.png
      h5topng -m 0 -M 1 -y $i -S $s $f
      mv $f.png $f:r-p8-y$i.$f:e.png
      h5topng -m 0 -M 1 -z $i -S $s $f
      mv $f.png $f:r-p8-z$i.$f:e.png
      @ i = $i + 1
   end
end

rm *hdf5

test_parallel_jacobi 16 16 2

foreach f (*hdf5)
   set i = 0
   while ($i < 18)
      h5topng -m 0 -M 1 -x $i -S $s $f
      mv $f.png $f:r-p1-x$i.$f:e.png
      h5topng -m 0 -M 1 -y $i -S $s $f
      mv $f.png $f:r-p1-y$i.$f:e.png
      h5topng -m 0 -M 1 -z $i -S $s $f
      mv $f.png $f:r-p1-z$i.$f:e.png
      @ i = $i + 1
   end
end


