#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import ('parallel_type')

#------------------------------
# DEPENDENCIES
#------------------------------

libraries  = ['hdf5']

#------------------------------
# ENVIRONMENTS
#------------------------------

env = env.Clone(LIBS=[libraries])

#------------------------------
# SOURCE
#------------------------------

includes   = [Glob('parallel_*hpp')]
sources    = [Glob('parallel_*cpp')]

#------------------------------
# TARGETS
#------------------------------

libraries = env.Library ([sources])
test_parallel_jacobi =  env.Program (['test_parallel_jacobi.cpp',      sources])
tests = [test_parallel_jacobi];

if (parallel_type == "charm"):
	test = 'test_parallel_jacobi'
	env.CharmBuilder(test + '.decl.h',test + '.ci',ARG = test)
	env.Depends(env.Object(test + '.cpp'),test + '.decl.h')

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-inc',env.Install ('#/include',includes))
env.Alias('install-lib',env.Install ('#/lib',    libraries))
env.Alias('install-bin',env.Install ('#/bin',    tests))


