#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import ('type')

#------------------------------
# DEPENDENCIES
#------------------------------

libraries  = ['hdf5']

#------------------------------
# ENVIRONMENTS
#------------------------------

env = env.Clone(LIBS=[libraries])

#------------------------------
# SOURCE
#------------------------------

includes   = [Glob('parallel_*hpp')]
sources    = [Glob('parallel_*cpp')]

#------------------------------
# TARGETS
#------------------------------

libraries = env.Library ([sources])
test_parallel_jacobi =  env.Program (['test_parallel_jacobi.cpp',      sources])
binaries = [test_parallel_jacobi];

if (type == "charm"):
	test = 'test_parallel_jacobi'
	env.CharmBuilder(test + '.decl.h',test + '.ci',ARG = test)
	env.CharmBuilder(test + '.def.h',test + '.ci',ARG = test)

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-inc',env.Install ('#/include',  includes))
env.Alias('install-lib',env.Install ('#/lib/'+type,libraries))
env.Alias('install-bin',env.Install ('#/bin/'+type,binaries))


