Import('env')

includes = [Glob('simulation*hpp')]

env.Alias('install-inc',env.Install ('$CPPPATH',includes))

sources  = []

env.Library ('simulation', [sources])
env.Library ('cello',      [sources])
env.Precious ('cello')
env.Alias('install-lib',env.Install ('$LIBPATH','libsimulation.a'))



