Import('env')

includes = [Glob('simulation*hpp')]

env.Alias('install-inc',env.Install ('#/include',includes))

sources  = []

libraries = env.Library ('simulation', [sources])

env.Alias('install-lib',env.Install ('#/lib',libraries))



