Import('env')

includes = [Glob('simulation*hpp')]
sources  = [Glob("simulation*cpp")]
components = ['error',
              'parameters',
              'parallel', 
              'monitor', 
              'memory', 
              'enzo',
              'user', 
              'user-ppm', 
              'data', 
              'field', 
              'cello',
	      '$FORTRANLIBS']
libraries = ['png','boost_thread-mt']

env = env.Clone(LIBS=[components,libraries])

libraries = env.Library ('simulation', [sources])

test_simulation = env.Program (['test_Simulation.cpp',sources])
tests = [test_simulation];


env.Alias('install-bin',env.Install ('$BINPATH', tests))
env.Alias('install-inc',env.Install ('#/include',includes))
env.Alias('install-lib',env.Install ('#/lib',libraries))



