#!/bin/csh -f

rm -f out.scons.* fail.scons.*

if ($#argv >= 1) then
  set platforms = ($argv)
else
  set platforms = (charm serial ampi mpi)
endif

printf "\n[ $platforms ]\n\n"
set p = 1

# clear

printf "cleaning..."
foreach platform ($platforms)
   setenv CELLO_PLATFORM linux-$platform
   scons -c >& /dev/null
end
printf "\n\n"

foreach platform ($platforms)
   setenv CELLO_PLATFORM linux-$platform

   set time = `date +"%Y-%m-%d %H:%M:%S"`
   printf "$time "
   printf "%10s" "${platform}: "
   # compile
   scons -k -j$p >& out.scons.$platform
   # count fails
   grep FAIL test/$platform-*unit |sort > fail.$platform
   grep pass test/$platform-*unit |sort > pass.$platform
   set p = `cat pass.$platform | wc -l`
   set f = `cat fail.$platform | wc -l`
   printf "FAIL: %d  Pass: %d\n" $f $p
   # check if any tests didn't finish
   grep "UNIT TEST" test/$platform-*unit | sed 's/BEGIN/END/' | uniq -u

end

echo

grep Segmentation out.*

echo


