#!/bin/csh -f

rm -f out.scons.* fail.scons.*

if ($#argv >= 1) then
  set platforms = $argv[1]
else
  set platforms = (charm serial mpi ampi)
endif

echo "$platforms"
set p = 1

foreach platform ($platforms)

   set platform = linux-$platform
   echo $platform
   setenv CELLO_PLATFORM $platform
   # clear
   scons -c >& /dev/null
   # compile
   scons -j$p >& out.scons.$platform
   # count fails
   grep FAIL test/*unit > fail.scons.$platform
   wc fail.scons.$platform
   # check if any tests didn't finish
   grep "UNIT TEST" test/*unit | sed 's/BEGIN/END/' | uniq -u

end

grep Segmentation out.*


