Import('env')
Import('parallel_run')
Import('serial_run')
Import('ip_charm')

Import('bin_path')
Import('test_path')

#----------------------------------------------------------
#defines
#----------------------------------------------------------

env['CPIN'] = 'touch parameters.out; mv parameters.out ${TARGET}.in'
env['RMIN'] = 'rm -f parameters.out'
env['clocal_cmd'] = '++local'


date_cmd = 'echo $TARGET > test/STATUS; echo "---------------------"; date +"%Y-%m-%d %H:%M:%S";'

make_movie = Builder(action = "png2swf -r 5 -o $TARGET ${ARGS} ")
png_to_gif = Builder(action = "convert -delay 5 -loop 0 ${ARGS} $TARGET ")

env.Append(BUILDERS = { 'MakeMovie' : make_movie})
env.Append(BUILDERS = { 'pngToGif'  : png_to_gif})


run_cosmology_1 = Builder(action = "$RMIN; " + date_cmd + serial_run + " $SOURCE $ARGS > $TARGET 2>&1; $CPIN; $COPY")
env.Append(BUILDERS = { 'RunCosmology_1' : run_cosmology_1 } )
env_mv_cosmology_1 = env.Clone(COPY = 'mkdir -p ' + test_path + '/MethodCosmology/Cosmology-1; mv `ls *.png *.h5` ' + test_path + '/MethodCosmology/Cosmology-1')


run_cosmology_8 = Builder(action = "$RMIN; " + date_cmd + parallel_run + " $SOURCE $clocal_cmd  $ARGS " + " > $TARGET 2>&1; $CPIN; $COPY")
env.Append(BUILDERS = { 'RunCosmology_8' : run_cosmology_8 } )
env_mv_cosmology_8 = env.Clone(COPY = 'mkdir -p ' + test_path + '/MethodCosmology/Cosmology-8; mv `ls *.png *.h5` ' + test_path + '/MethodCosmology/Cosmology-8')


#-------------------------------------------------------------
#load balancing
#-------------------------------------------------------------

#serial
balance_cosmology_1 = env_mv_cosmology_1.RunCosmology_1 (
     'test_method_cosmology-1.unit',
     bin_path + '/enzo-p',
     ARGS='input/Cosmology/method_cosmology-1.in')

Clean(balance_cosmology_1,
     [Glob('#/' + test_path + '/Dir_COSMO-1'),
      Glob('#/' + test_path + '/Dir_COSMO-1')])

#env.MakeMovie("method_cosmology-1.swf", "test_method_cosmology-1.unit", \
#              ARGS = test_path + '/method_cosmology-1*.png");
#env.PngToGif("method_cosmology-1.gif", "test_method_cosmology-1.unit", \
#              ARGS = test_path + '/method_cosmology-1*.png");


#parallel

balance_cosmology_8 = env_mv_cosmology_8.RunCosmology_8 (
     'test_method_cosmology-8.unit',
     bin_path + '/enzo-p',
     ARGS='input/Cosmology/method_cosmology-8.in')

Clean(balance_cosmology_8,
     [Glob('#/' + test_path + '/Dir_COSMO-8'),
      Glob('#/' + test_path + '/Dir_COSMO-8')])

#env.MakeMovie("method_cosmology-8.swf", "test_method_cosmology-8.unit", \
#              ARGS = test_path + '/method_cosmology-8*.png");
#env.PngToGif("method_cosmology-8.gif", "test_method_cosmology-8.unit", \
#              ARGS = test_path + '/method_cosmology-8*.png");
