Import('env')

components = ['user','field', 'parameters', 'error','disk','memory','monitor','parallel','method','cello']
libraries  = ['hdf5', 'png','boost_thread-mt', '$FORTRANLIBS']

env = env.Clone (LIBS = [components,libraries])

sources  = [Glob('initialize*cpp'),
            Glob('Cosmology*.cpp'),
            Glob('Grid_*cpp'),
            Glob('*.F'),
           'cello_hydro.cpp',
           'c_message.cpp',
           'data_dump.cpp',
	   'image_dump.cpp',
	   'FindField.cpp',
           'SetExternalBoundary.cpp',
           'sum_field.cpp']



binaries = [env.Program (['test_ppm.cpp',      sources])]

libraries = env.Library ('user-ppm', sources)

env.Alias('install-bin', env.Install ('$BINPATH', binaries))
env.Alias('install-lib',env.Install ('#/lib',    libraries))
