Import('env')

components = ['user','field', 'parameters', 'error','disk','memory','monitor','parallel','cello']
libraries  = ['hdf5', 'png','boost_thread-mt', '$FORTRANLIBS']

env = env.Clone (LIBS = [components,libraries])

sources  = [Glob('initialize*cpp'),
            Glob('Cosmology*.cpp'),
            Glob('Grid_*cpp'),
            Glob('*.F'),
	   '../image_dump.cpp',
           '../SetExternalBoundary.cpp',
	   'FindField.cpp',
           'sum_field.cpp',
	   '../initialize_hydro.cpp']

#'../data_dump.cpp',
#'../cello_hydro.cpp',
#'../write_hydro.cpp', 

binaries = [env.Program (['test_ppm.cpp',      sources])]

libraries = env.Library ('user-ppm', sources)

env.Alias('install-bin', env.Install ('$BINPATH', binaries))
env.Alias('install-lib',env.Install ('#/lib',    libraries))
