Import('env')

components = ['error','disk','memory','monitor','parallel','method']
libraries  = ['hdf5', 'png', '$FORTRANLIBS']

env = env.Clone (LIBS = [components,libraries])

includes   = ['method_MethodEnzoPpm.hpp']

sources_ppm  = [Glob('initialize*cpp'),
            Glob('Cosmology*.cpp'),
            Glob('Grid_*cpp'),
            Glob('*.F'),
           'method_MethodEnzoPpm.cpp',
           'cello_hydro.cpp',
           'c_message.cpp',
           'data_dump.cpp',
	   'image_dump.cpp',
	   'FindField.cpp',
           'SetExternalBoundary.cpp',
           'sum_field.cpp']

Export('sources_ppm')

env.Alias('install-inc',env.Install ('#/include',includes))


binaries = [env.Program (['test_ppm.cpp',      sources_ppm]),
            env.Program (['test_enzo_ppm.cpp', sources_ppm])]

env.Alias('install-bin', env.Install ('$BINPATH', binaries))
