#!/bin/tcsh -f

set min_density = 0.125
set max_density = 1.000

# set color = /usr/share/h5utils/colormaps/jet
set color = /usr/share/h5utils/colormaps/jet

foreach hdf5 (*.hdf5)
foreach field (density)
   echo $hdf5
   h5topng -d $field -T -m 0.125 -M 1.0 -c $color $hdf5
   mv $hdf5.png $field-$hdf5.png
end
end

