Import('env')
Import('parallel_run')
Import('serial_run')
Import('ip_charm')

Import('bin_path')
Import('test_path')

#----------------------------------------------------------
#defines
#----------------------------------------------------------

env['CPIN'] = 'touch parameters.out; mv parameters.out ${TARGET}.in'
env['RMIN'] = 'rm -f parameters.out'

date_cmd = 'echo $TARGET > test/STATUS; echo "---------------------"; date +"%Y-%m-%d %H:%M:%S";'

run_enzo_units = Builder(action = "$RMIN; " + date_cmd + serial_run + " $SOURCE $ARGS > $TARGET 2>&1; $CPIN; $COPY")
env.Append(BUILDERS = { 'RunEnzoUnits' : run_enzo_units } )
env_mv_enzo_units = env.Clone(COPY = 'mkdir -p ' + test_path + '/UnitsComponent/EnzoUnits; mv `ls *.png *.h5` ' + test_path + '/UnitsComponent/EnzoUnits')

#-------------------------------------------------------------
#load balancing
#-------------------------------------------------------------


balance_enzo_units = env_mv_enzo_units.RunEnzoUnits (
     'test_EnzoUnits.unit',
     bin_path + '/test_EnzoUnits')

