Import('env')

components = ['user','field', 'parameters', 'error','disk','memory','monitor','parallel','cello']
libraries  = ['hdf5', 'png','boost_thread-mt', '$FORTRANLIBS']

env = env.Clone(LIBS = [components,libraries])

# not supported by older scons
# env.SetOption('warn', 'no-fortran-cxx-mix')

sources = [
        Glob('Cosmology*cpp'),
        Glob('Grid_*cpp'),
        Glob('initialize_*cpp'),
	'../image_dump.cpp',
        '../initialize_hydro.cpp',
	'../SetExternalBoundary.cpp',
	'PPML_Conservative.F',
	'PPML_HLLD.F',
	'PPML_MAIN.F',
	'PPML_monot.F',
	'PPML_potokx.F',
	'PPML_potoky.F',
	'PPML_potokz.F',
	'PPML_Primitive.F',
	'PPML_sub.F',
	'PPML_TimeStep.F']

#'../data_dump.cpp',
#'../cello_hydro.cpp',

binaries  = [env.Program (['test_ppml.cpp',      sources])]

libraries = env.Library ('enzo-ppml', sources)

env.Alias('install-bin', env.Install ('#/bin', binaries))
env.Alias('install-lib',env.Install ('#/lib',    libraries))







