#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import('type')

Import('bin_path')
Import('inc_path')
Import('lib_path')

#------------------------------
# DEPENDENCIES
#------------------------------

components = ['disk',
              'error', 'monitor', 'performance',
              'test','cello']
libraries  = ['hdf5']

#------------------------------
# SOURCE
#------------------------------

includes = [Glob('disk*hpp')]
sources  = [Glob('disk*cpp')]

#------------------------------
# ENVIRONMENTS
#------------------------------

env = env.Clone(LIBS=[components,libraries])

#------------------------------
# TARGETS
#------------------------------

libraries  = env.Library ('disk', sources)

charm_main = []
if (type == "charm"):
   charm_main = ['../Main/main.cpp']

test_FileHdf5  = env.Program (['test_FileHdf5.cpp',  charm_main])
test_FileIfrit = env.Program (['test_FileIfrit.cpp', charm_main])

binaries = [test_FileHdf5,test_FileIfrit]

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-bin',env.Install (bin_path,binaries))
env.Alias('install-inc',env.Install (inc_path,includes))
env.Alias('install-lib',env.Install (lib_path,libraries))



