#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import('type')

#------------------------------
# DEPENDENCIES
#------------------------------

components = ['error', 'monitor', 'performance',
              'test','cello']
libraries  = ['hdf5', 'png']

#------------------------------
# SOURCE
#------------------------------

includes = [Glob('disk*hpp')]
sources  = [Glob('disk*cpp')]

#------------------------------
# ENVIRONMENTS
#------------------------------

env = env.Clone(LIBS=[components,libraries])

#------------------------------
# TARGETS
#------------------------------

libraries  = env.Library ('disk', sources)

if (type == "charm"):
	sources = sources + ['../main.cpp']

test_FileHdf5  = env.Program (['test_FileHdf5.cpp', sources])
test_FileIfrit = env.Program (['test_FileIfrit.cpp', sources])

binaries = [test_FileHdf5,test_FileIfrit]

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-inc',env.Install ('#/include',  includes))
env.Alias('install-lib',env.Install ('#/lib/'+type,libraries))
env.Alias('install-bin',env.Install ('#/bin/'+type,binaries))



