#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import('use_papi')

Import('bin_path')
Import('inc_path')
Import('lib_path')

#------------------------------
# DEPENDENCIES
#------------------------------

components = []

components.append(['charm'])

components.append(['enzo3','simulation', 'problem',
	      'comm', 'control', 'mesh', 'field',
	      'io', 'disk','memory',
	      'parameters', 
	      'error', 'monitor', 'parallel','performance',
	      'test','cello','external'])

if (use_papi):
	components.append(['papi','pfm'])


components.append(['hdf5','z'])

libraries  = ['png','grackle','$FORTRANLIBS']

#------------------------------
# INCLUDES
#------------------------------

includes = [Glob('enzo3*hpp')]

#------------------------------
# SOURCES
#------------------------------

sources  = [Glob('enzo3*cpp')]

#------------------------------
# ENVIRONMENTS
#------------------------------

env = env.Clone(LIBS=[components,libraries])

#------------------------------
# TARGETS
#------------------------------

libraries   = env.Library ('enzo3', sources)

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-inc',env.Install (inc_path,includes))
env.Alias('install-lib',env.Install (lib_path,libraries))



