#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import('use_papi')

Import('bin_path')
Import('inc_path')
Import('lib_path')

#------------------------------
# DEPENDENCIES
#------------------------------

components = []

components.append(['charm'])

components.append(['enzo3','simulation', 'problem',
	      'comm', 'control', 'mesh', 'field',
	      'io', 'disk','memory',
	      'parameters', 
	      'error', 'monitor', 'parallel','performance',
	      'test','cello','external'])

if (use_papi):
	components.append(['papi','pfm'])


components.append(['hdf5','z'])

libraries  = ['png','grackle','$FORTRANLIBS']

#------------------------------
# SOURCE
#------------------------------

includes = [Glob('*enzo3*hpp'),'fortran.h']

sources  = [Glob('enzo3_*cpp')]


charm_main = []
includes.append(['enzo.decl.h','enzo.def.h'])
charm_main = ['../Cello/main_enzo.cpp']

#------------------------------
# ENVIRONMENTS
#------------------------------

env = env.Clone(LIBS=[components,libraries])

#------------------------------
# TARGETS
#------------------------------

libraries   = env.Library ('enzo', sources)

test_enzo_p = env.Program (['enzo-p.cpp', charm_main])

test_enzo_prolong = env.Program (['test_Prolong.cpp', charm_main])

binaries = [test_enzo_p, test_enzo_prolong]

env.CharmBuilder(['enzo.decl.h','enzo.def.h'],'enzo.ci',ARG = 'enzo')
# env.CharmBuilder(['main_enzo.decl.h','main_enzo.def.h'],
# 	'main_enzo.ci',ARG = 'main_enzo')

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-bin',env.Install (bin_path,binaries))
env.Alias('install-bin',env.Install ('#/bin/',binaries))

env.Alias('install-inc',env.Install (inc_path,includes))
env.Alias('install-lib',env.Install (lib_path,libraries))



