Import('env')

components = ['error','disk','memory','monitor','parallel','method']
libraries  = ['hdf5', 'png', '$FORTRANLIBS']

env = env.Clone (LIBS = [components,libraries])

includes   = ['enzo_ppm.hpp']
sources  = [Glob('initialize*cpp'),
            Glob('Cosmology*.cpp'),
            Glob('Grid_*cpp'),
            Glob('*.F'),
           'enzo_ppm.cpp',
           'cello_hydro.cpp',
           'c_message.cpp',
           'data_dump.cpp',
	   'image_dump.cpp',
	   'FindField.cpp',
           'SetExternalBoundary.cpp',
           'sum_field.cpp']

env.Alias('install-inc',env.Install ('#/include',includes))


env.Library ('enzo-ppm', [sources])

binaries = [env.Program (['test_ppm.cpp',      sources]),
            env.Program (['test_enzo_ppm.cpp', sources])]

env.Alias('install-bin', env.Install ('$BINPATH', binaries))
