Import('env')

includes  = [Glob('*hpp')]

libraries = env.Library ('user', 'Enzo/libuser-enzo.a')

env.Alias('install-inc',env.Install ('#/include',includes))
env.Alias('install-lib',env.Install ('#/lib',libraries))

SConscript('Enzo/SConscript')



