Import('env')

SConscript('Enzo/SConscript')

env.Alias('install-inc',env.Install ('$CPPPATH',[Glob('*hpp')]))

lib_user = env.Library ('user', 'Enzo/libuser-enzo.a')
env.Alias('install-lib',env.Install ('$LIBPATH',lib_user))




