Import('env')

includes = [Glob('*hpp')]
sources  = [Glob('method*cpp')]

env.Alias('install-inc',env.Install ('#/include',includes))

SConscript('ppm/SConscript')
SConscript('ppml/SConscript')

libraries = env.Library ('user', sources)
env.Alias('install-lib',env.Install ('#/lib',    libraries))



