#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import('type')

#------------------------------
# DEPENDENCIES
#------------------------------

components = ['parallel',
	      'monitor',
	      'error','performance', 
	      'test','cello']

libraries  = ['png']

#------------------------------
# SOURCE
#------------------------------

includes = [Glob('parameters*hpp'),'parse.h']
sources  = ['parse.tab.c', 'lex.yy.c', Glob('parameters*cpp') ]

#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# Uncomment when parse.l or parse.y change
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# env.CFile(target = 'lex.yy.c', source = 'parse.l')
# env.CFile(target = ['parse.tab.c', 'parse.tab.h'], source = 'parse.y', YACCFLAGS='-d -t')
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

#------------------------------
# ENVIRONMENTS
#------------------------------

env = env.Clone(LIBS=[components,libraries])

#------------------------------
# TARGETS
#------------------------------

libraries = env.Library ('parameters', [sources])

if (type == "charm"):
	sources = sources + ["../main.cpp"]

test_parameters = env.Program (['test_Parameters.cpp', sources])
test_parse      = env.Program (['test_Parse.cpp',      sources])

binaries = [test_parameters, test_parse]

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-inc',env.Install ('#/include',  includes))
env.Alias('install-lib',env.Install ('#/lib/'+type,libraries))
env.Alias('install-bin',env.Install ('#/bin/'+type,binaries))



