Import('env')

components = ['error']
env = env.Clone(LIBS=[components])

includes = [
	'parameters.hpp',
	'parameters_parameters.hpp',
	'param.hpp',
	'parse.h']

env.Alias('install-inc',env.Install ('#/include',includes))

sources  = ['parse.tab.c', 'lex.yy.c', 'param.cpp', Glob('parameters*cpp') ]

# env.CFile(target = ['parse.tab.c', 'parse.tab.h'], 
#           source = 'parse.y',
#           YACCFLAGS='-d')

# env.CFile(target = 'lex.yy.c', source = 'parse.l')

libraries = env.Library ('parameters', [sources])

env.Alias('install-lib',env.Install ('#/lib',libraries))

test_parameters = env.Program (['test_parameters.cpp', sources])
test_parse      = env.Program (['test_parse.cpp', sources])
inputs          = Glob('*.in')
env.Alias('install-bin', env.Install ('$BINPATH', 
	[test_parameters, test_parse, inputs]))




