Import('env')
Import('parallel_run')
Import('serial_run')
Import('ip_charm')

Import('bin_path')
Import('test_path')

#----------------------------------------------------------
#defines
#----------------------------------------------------------

env['CPIN'] = 'touch parameters.out; mv parameters.out ${TARGET}.in'
env['RMIN'] = 'rm -f parameters.out'

date_cmd = 'echo $TARGET > test/STATUS; echo "---------------------"; date +"%Y-%m-%d %H:%M:%S";'

run_array = Builder(action = "$RMIN; " + date_cmd + serial_run + " $SOURCE $ARGS > $TARGET 2>&1; $CPIN; $COPY")
env.Append(BUILDERS = { 'RunArray' : run_array } )
env_mv_array = env.Clone(COPY = 'mkdir -p ' + test_path + '/ArrayComponent/CelloArray; mv `ls *.png *.h5` ' + test_path + '/ArrayComponent/CelloArray')

#-------------------------------------------------------------
#load balancing
#-------------------------------------------------------------


env_mv_array.RunArray (
     'test_CelloArray.unit',
     bin_path + '/test_CelloArray')