Import('env')
Import('parallel_run')
Import('serial_run')
Import('ip_charm')

Import('bin_path')
Import('test_path')

#----------------------------------------------------------
#defines
#----------------------------------------------------------

env['CPIN'] = 'touch parameters.out; mv parameters.out ${TARGET}.in'
env['RMIN'] = 'rm -f parameters.out'

date_cmd = 'echo $TARGET > test/STATUS; echo "---------------------"; date +"%Y-%m-%d %H:%M:%S";'

run_error = Builder(action = "$RMIN; " + date_cmd + serial_run + " $SOURCE $ARGS > $TARGET 2>&1; $CPIN; $COPY")
env.Append(BUILDERS = { 'RunError' : run_error } )
env_mv_error = env.Clone(COPY = 'mkdir -p ' + test_path + '/ErrorComponent/Error; mv `ls *.png *.h5` ' + test_path + '/ErrorComponent/Error')

#-------------------------------------------------------------
#load balancing
#-------------------------------------------------------------


env_mv_error.RunError (
     'test_Error.unit',
     bin_path + '/test_Error')