Import('env')

includes   = [Glob('parallel*hpp')]
sources    = [Glob('parallel*cpp')]
libraries  = ['error','png']

env = env.Clone(LIBS=[libraries])

libraries = env.Library ('parallel', [sources])

test_mpi      = env.Program (['test_Mpi.cpp',      sources])
test_affinity = env.Program (['test_Affinity.cpp', sources])
test_layout   = env.Program (['test_Layout.cpp',   sources])

tests = [test_mpi, test_affinity, test_layout];

env.Alias('install-inc',env.Install ('#/include',includes))
env.Alias('install-lib',env.Install ('#/lib',    libraries))
env.Alias('install-bin',env.Install ('$BINPATH', tests))


