
SConscript('jacobi/SConscript')

#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import('parallel_type')

#------------------------------
# DEPENDENCIES
#------------------------------

libraries  = ['error','png']

#------------------------------
# ENVIRONMENTS
#------------------------------

env = env.Clone(LIBS=[libraries])

#------------------------------
# SOURCE
#------------------------------

includes   = [Glob('parallel*hpp'),'parallel.def']
sources    = [Glob('parallel*cpp')]

#------------------------------
# TARGETS
#------------------------------

libraries = env.Library ('parallel', [sources])
test_GroupProcessMpi  =  env.Program (['test_GroupProcessMpi.cpp',    sources])
test_mpi              = env.Program (['test_Mpi.cpp',      sources])
# test_ParallelAffinity = env.Program (['test_ParallelAffinity.cpp', sources])
# test_ParallelLayout   = env.Program (['test_ParallelLayout.cpp',   sources])

tests = [test_GroupProcessMpi];

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-inc',env.Install ('#/include',includes))
env.Alias('install-lib',env.Install ('#/lib',    libraries))
env.Alias('install-bin',env.Install ('#/bin',    tests))


