Import('env')
Import('parallel_run')
Import('serial_run')
Import('ip_charm')

Import('bin_path')
Import('test_path')

#----------------------------------------------------------
#defines
#----------------------------------------------------------

env['CPIN'] = 'touch parameters.out; mv parameters.out ${TARGET}.in'
env['RMIN'] = 'rm -f parameters.out'



date_cmd = 'echo $TARGET > test/STATUS; echo "---------------------"; date +"%Y-%m-%d %H:%M:%S";'

make_movie = Builder(action = "png2swf -r 5 -o $TARGET ${ARGS} ")
png_to_gif = Builder(action = "convert -delay 5 -loop 0 ${ARGS} $TARGET ")

env.Append(BUILDERS = { 'MakeMovie' : make_movie})
env.Append(BUILDERS = { 'pngToGif'  : png_to_gif})


run_mesh = Builder(action = "$RMIN; " + date_cmd + serial_run + " $SOURCE $ARGS > $TARGET 2>&1; $CPIN; $COPY")
env.Append(BUILDERS = { 'RunMesh' : run_mesh } )
env_mv_mesh = env.Clone(COPY = 'mkdir -p ' + test_path + '/MethodHeat/Heat-1; mv `ls *.png *.h5` ' + test_path + '/MethodHeat/Heat-1')


#-------------------------------------------------------------
#load balancing
#-------------------------------------------------------------

#serial
balance_mesh = env_mv_mesh.RunMesh (
     'test_mesh-balanced.unit',
     bin_path + '/enzo-p',
     ARGS='input/Balance/mesh-balanced.in')

Clean(balance_mesh,
     [Glob('#/' + test_path + '/mesh-balanced*.png')])


