current:ps
PAPER = `pwd | awk 'BEGIN{FS="/"}{print $$NF}'`

ps:dvi
	dvips -o $(PAPER).ps $(PAPER).dvi
ps2:ps
	a2ps -2 $(PAPER).ps -o $(PAPER)2.ps
pdf:dvi
	dvipdf $(PAPER).dvi $(PAPER).pdf
pdf2:ps2
	ps2pdf $(PAPER)2.ps $(PAPER)2.pdf
2up: ps
	a2ps -M Letter -2 -o $(PAPER)2.ps $(PAPER).ps

dvi: include.tex
	-latex $(PAPER)

include.tex:
	ln -s ../include.tex .

clean:
	-@rm -f *~ $(PAPER).dvi *.aux $(PAPER).log $(PAPER).ps $(PAPER).pdf
