current:pdf html

PAPER = `pwd | awk 'BEGIN{FS="/"}{print $$NF}'`

#-----------------------------------------------------------------------
# BUILD
#-----------------------------------------------------------------------

pdf: include.tex uml figures
	pdflatex $(PAPER).tex
	pdflatex $(PAPER).tex
	$(MAKE) install-pdf
html:
	tth -e2 $(PAPER).tex > $(PAPER).html
	$(MAKE) install-html


#-----------------------------------------------------------------------
# BIBLIOGRAPHY
#-----------------------------------------------------------------------

bib: 
	bibtex $(PAPER)

#-----------------------------------------------------------------------
# LINKS
#-----------------------------------------------------------------------

.PHONY: figures
figures:
	-@ln -s ../figures/* .
uml:
	ln -s ../uml .
	$(MAKE) -C uml
include.tex:
	ln -s ../include.tex .

#-----------------------------------------------------------------------
# INSTALL
#-----------------------------------------------------------------------

.PHONY: install-%

install-pdf:
	if [ ! -e ../pdf ]; then mkdir ../pdf; fi
	cp $(PAPER).pdf ../pdf
install-html:
	if [ ! -e ../html ]; then mkdir ../html; fi
	cp $(PAPER).html ../html

#-----------------------------------------------------------------------
# CLEAN
#-----------------------------------------------------------------------

clean:
	-@rm -f *~ *.aux \
        $(PAPER).bbl \
        $(PAPER).blg \
        $(PAPER).dvi \
        $(PAPER).html \
        $(PAPER).log \
        $(PAPER).nav \
        $(PAPER).out \
        $(PAPER).pdf \
        $(PAPER).ps \
        $(PAPER).snm \
        $(PAPER).toc \
        $(PAPER).vrb

distclean: clean
	-@rm uml include.tex 
#	-@rm makefile # Must be last!
