current:pdf2 html
PAPER = `pwd | awk 'BEGIN{FS="/"}{print $$NF}'`

ps:dvi
	dvips -o $(PAPER).ps $(PAPER).dvi
	$(MAKE) install-ps
html:
	tth -e2 $(PAPER).tex > $(PAPER).html
	$(MAKE) install-html
pdf:dvi
	dvipdf $(PAPER).dvi $(PAPER).pdf
	$(MAKE) install-pdf

pdf2: include.tex uml figures
	pdflatex $(PAPER).tex
	$(MAKE) install-pdf

dvi: include.tex uml figures
	$(MAKE) -C uml
	-latex $(PAPER)
bib: 
	bibtex $(PAPER)

pdfimg: include.tex uml figures
	$(MAKE) -C uml
	-pdflatex $(PAPER)
uml:
	ln -s ../uml .
.PHONY: figures
figures:
	-@ln -s ../figures/* .

include.tex:
	ln -s ../include.tex .

glo:
	makeindex $(PAPER).glo -s $(PAPER).ist -t $(PAPER).glg -o $(PAPER).gls

.PHONY: install-%

install-pdf:
	cp $(PAPER).pdf ../pdf
install-ps:
	cp $(PAPER).ps ../ps
install-html:
	cp $(PAPER).html ../html

clean:
	-@rm -f *~ *.aux \
        $(PAPER).dvi \
        $(PAPER).log \
        $(PAPER).ps \
        $(PAPER).pdf \
        $(PAPER).html \
        $(PAPER).snm \
        $(PAPER).nav \
        $(PAPER).out \
        $(PAPER).toc
distclean: clean
	-@rm uml include.tex 
	-@rm makefile # Must be last!
