Import('env')

components = ['error','parallel']

env = env.Clone(LIBS=components)


includes = [Glob('array*hpp')]

sources  = [Glob('array*cpp')]

libraries = env.Library ('array', [sources])

env.Alias('install-inc',env.Install ('#/include',includes))
env.Alias('install-lib',env.Install ('#/lib',    libraries))






