#!/bin/csh -f

set    n = $1
set file = $2
set axis = $3

set i = $n
@ i = - $i

while ($i < $n)

   if ($axis == 1) then
      cat $file | awk '{if ($1=='"$i"') print $2,$3,$4}' > axis-$n.$i.data
   endif

   if ($axis == 2) then
      cat $file | awk '{if ($2=='"$i"') print $1,$3,$4}' > axis-$n.$i.data
   endif

   if ($axis == 3) then
      cat $file | awk '{if ($3=='"$i"') print $1,$2,$4}' > axis-$n.$i.data
   endif

   @ i = $i + 1
end
