include Make.include

MPCPP = mpiCC
CPP = g++

# HYPRE

# hypre-2.0.0
HYPRE_PATH = $(HOME)/hypre
#hypre-2.4.0b
# HYPRE_PATH = /$(HOME)/packages/hypre-2.4.0b/src/hypre

HYPREDEF = 
HYPREINC = -I$(HYPRE_PATH)/include
HYPRELIB = -L$(HYPRE_PATH)/lib -lHYPRE 

