
TOP     = ../..
PACKAGE = field
OBJS    = 
TESTS   = 
DIRS    = 

include $(TOP)/src/MAKE/Make.include

#=======================================================================
# TARGETS
#=======================================================================

#-----------------------------------------------------------------------

.PHONY: install-include
install-include:
	ln -sf `pwd`/field.hpp $(INCLUDE)
	ln -sf `pwd`/field_field.hpp $(INCLUDE)

#-----------------------------------------------------------------------

.PHONY: clean-local
clean-local:

