#------------------------------
# IMPORTS
#------------------------------

Import('env')

#------------------------------
# DEPENDENCIES
#------------------------------

components = ['cello','error']

#------------------------------
# ENVIRONMENTS
#------------------------------

env = env.Clone(LIBS=components)

#------------------------------
# SOURCE
#------------------------------

includes = [Glob('field*hpp')]
sources  = [Glob('field*cpp')]

#------------------------------
# TARGETS
#------------------------------

libraries              = env.Library ('field', [sources])
test_field_descr       = env.Program (['test_FieldDescr.cpp',  sources])
test_field_block       = env.Program (['test_FieldBlock.cpp',  sources])
test_field_block_faces = env.Program (['test_FieldBlockFaces.cpp',  sources])

tests = [test_field_block, test_field_descr, test_field_block_faces]


#------------------------------
# INSTALL
#------------------------------

env.Alias('install-inc',env.Install ('#/include',includes))
env.Alias('install-lib',env.Install ('#/lib',    libraries))
env.Alias('install-bin',env.Install ('#/bin',    tests))




