#!/bin/tcsh

set OBJ = (O0 O1 O2 O3)

make clean
foreach obj ($OBJ)
   make time_matvec-$obj
end
foreach k (1 2)
foreach obj ($OBJ)
   echo "time_matvec-$obj >& time_matvec-$obj-$k.data"
   time_matvec-$obj >& time_matvec-$obj-$k.data
end
end
