#!/bin/tcsh

set MACH = datastar

set OBJ = (O0 O2 O3 O4 O5)

make clean
foreach obj ($OBJ)
   make time_matvec-$obj
end
foreach k (1 2)
foreach obj ($OBJ)
   echo "time_matvec-$obj >& matvec-$MACH-$obj-$k.data"
   time_matvec-$obj >& matvec-$MACH-$obj-$k.data
end
end
