#------------------------------
# DIRECTORIES
#------------------------------

#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import('type')
Import('use_papi')

#------------------------------
# DEPENDENCIES
#------------------------------

components = [ 
              'field', 
              'simulation','method', 'io',
              'disk','memory','parallel',
              'parameters',
              'error','monitor','performance', 
              'test','cello']

if (use_papi):
	components = components + ['papi','pfm']

libraries  = ['hdf5','png'] # used only for test_TreeK(?)

#if (type == "charm"):
#   components = components + ['enzo']

#------------------------------
# SOURCE
#------------------------------

includes = [Glob('mesh*hpp')]
sources  = [Glob('mesh*cpp')]
sources_tree = [Glob('mesh*Node*cpp'), Glob('mesh*Tree*cpp')]

#------------------------------
# ENVIRONMENTS
#------------------------------

env = env.Clone(LIBS=[components,libraries])

#------------------------------
# TARGETS
#------------------------------

libraries = env.Library ('mesh', [sources])

# if (type == "charm"):
#    sources = sources + ['../main_mesh.cpp']

test_block     = env.Program (['test_Block.cpp', sources])
test_hierarchy = env.Program (['test_Hierarchy.cpp',  sources])
test_patch     = env.Program (['test_Patch.cpp', sources])
test_tree      = env.Program (['test_TreeK.cpp', sources_tree])

if (type == "charm"):
   env.CharmBuilder('mesh.decl.h','mesh.ci',ARG = 'mesh')
   env.CharmBuilder('mesh.def.h', 'mesh.ci',ARG = 'mesh')
   includes = includes + ['mesh.decl.h','mesh.def.h']

binaries = [test_hierarchy, test_patch, test_block, test_tree ];

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-inc',env.Install ('#/include',  includes))
env.Alias('install-lib',env.Install ('#/lib/'+type,libraries))
env.Alias('install-bin',env.Install ('#/bin/'+type,binaries))
