Import('env')
Import('parallel_run')
Import('serial_run')
Import('ip_charm')

Import('bin_path')
Import('test_path')

#----------------------------------------------------------
#defines
#----------------------------------------------------------

env['CPIN'] = 'touch parameters.out; mv parameters.out ${TARGET}.in'
env['RMIN'] = 'rm -f parameters.out'
env['clocal_cmd'] = '++local'


date_cmd = 'echo $TARGET > test/STATUS; echo "---------------------"; date +"%Y-%m-%d %H:%M:%S";'

make_movie = Builder(action = "png2swf -r 5 -o $TARGET ${ARGS} ")
png_to_gif = Builder(action = "convert -delay 5 -loop 0 ${ARGS} $TARGET ")

env.Append(BUILDERS = { 'MakeMovie' : make_movie})
env.Append(BUILDERS = { 'pngToGif'  : png_to_gif})


run_heat_1 = Builder(action = "$RMIN; " + date_cmd + serial_run + " $SOURCE $ARGS > $TARGET 2>&1; $CPIN; $COPY")
env.Append(BUILDERS = { 'RunHeat_1' : run_heat_1 } )
env_mv_heat_1 = env.Clone(COPY = 'mkdir -p ' + test_path + '/MethodHeat/Heat-1; mv `ls *.png *.h5` ' + test_path + '/MethodHeat/Heat-1')


run_heat_8 = Builder(action = "$RMIN; " + date_cmd + parallel_run + " $SOURCE $clocal_cmd  $ARGS " + " > $TARGET 2>&1; $CPIN; $COPY")
env.Append(BUILDERS = { 'RunHeat_8' : run_heat_8 } )
env_mv_heat_8 = env.Clone(COPY = 'mkdir -p ' + test_path + '/MethodHeat/Heat-8; mv `ls *.png *.h5` ' + test_path + '/MethodHeat/Heat-8')


#-------------------------------------------------------------
#load balancing
#-------------------------------------------------------------

#serial
balance_heat_1 = env_mv_heat_1.RunHeat_1 (
     'test_method_heat-1.unit',
     bin_path + '/enzo-e',
     ARGS='input/Heat/method_heat-1.in')

Clean(balance_heat_1,
     [Glob('#/' + test_path + '/Heat-1/method_heat*-1*.png'),
      Glob('#/' + test_path + '/Heat-1/method_heat*-1*.h5')])

env.MakeMovie("/Heat-1/method_heat-1.swf", "test_method_heat-1.unit", \
              ARGS = test_path + "/MethodHeat/Heat-1/method_heat*-1*.png");
env.PngToGif("/Heat-1/method_heat-1.gif", "test_method_heat-1.unit", \
              ARGS = test_path + "/MethodHeat/Heat-1/method_heat*-1*.png");


#parallel

balance_heat_8 = env_mv_heat_8.RunHeat_8 (
     'test_method_heat-8.unit',
     bin_path + '/enzo-e',
     ARGS='input/Heat/method_heat-8.in')

Clean(balance_heat_8,
     [Glob('#/' + test_path + '/Heat-8/method_heat*-8*.png'),
      Glob('#/' + test_path + '/Heat-8/method_heat*-8*.h5')])

env.MakeMovie("/Heat-8/method_heat-8.swf", "test_method_heat-8.unit", \
              ARGS = test_path + "/MethodHeat/Heat-8/method_heat*-8*.png");
env.PngToGif("/Heat-8/method_heat-8.gif", "test_method_heat-8.unit", \
              ARGS = test_path + "/MethodHeat/Heat-8/method_heat*-8*.png");
