#!/bin/csh -f

# DEBUG SCRIPT
#
# uses sum.c executable "s"
# directories $dir[], with corresponding block count $nb[]
#
# outputs field sums for $prefix FieldBlock::print()

set run = 1

set ENZO = (enzo-p)
set cycles = 100

set suffix=""

# ASSUMES $dir[1] is single-process
set dir = ( implosion.11 implosion.21 implosion.12)
set  nb = (1 2 2 )

foreach enzo ($ENZO)
if ($run == 1) then 
   set i = 1
   while ($i <= $#dir)
      echo "$enzo $dir[$i]"
      cd $dir[$i]
   
      charmrun +p $nb[$i] ../$enzo in.enzo-p > out.$enzo
   
      cd ..
      @ i = $i + 1
   end

endif
end

# Display average values of all fields (differences expected
# if ghost zones included in FieldBlock::print() )
foreach enzo ($ENZO)
set i = 1
while ($i <= $#dir)

   cd $dir[$i]
   set cycle = 1
   while ($cycle <= $cycles)
      set prefix = "`printf "%03d-A" $cycle`"

      awk "/$prefix "'\[density\]/     {print $3}' out.$enzo > d
      awk "/$prefix "'\[velocity_x\]/  {print $3}' out.$enzo > vx
      awk "/$prefix "'\[velocity_y\]/  {print $3}' out.$enzo > vy
      awk "/$prefix "'\[total_energy\]/{print $3}' out.$enzo > te

      echo "$prefix $dir[$i] $enzo " \
           "`../s $nb[$i] <d`" \
           "`../s $nb[$i] <vx`" \
           "`../s $nb[$i] <vy`" \
           "`../s $nb[$i] <te`"
      @ cycle = $cycle + 1
   end
   cd ..
   @ i = $i + 1
end
end

