Import('env')

components = ['error']
env = env.Clone(LIBS=[components])

includes = [Glob('*hpp')]

env.Alias('install-inc',env.Install ('#/include',includes))

sources  = [Glob('memory*cpp')]

libraries = env.Library ('memory', [sources])

env.Alias('install-lib',env.Install ('#/lib',libraries))

test_memory   = env.Program (['test_memory.cpp', sources])
env.Alias('install-bin', env.Install ('$BINPATH', test_memory))




