#------------------------------
# IMPORTS
#------------------------------

Import('env')

#------------------------------
# DEPENDENCIES
#------------------------------

components = ['error']

#------------------------------
# ENVIRONMENTS
#------------------------------

env = env.Clone(LIBS=[components])

#------------------------------
# SOURCE
#------------------------------

includes = [Glob('*hpp')]
sources  = [Glob('memory*cpp')]

#------------------------------
# TARGETS
#------------------------------

libraries   = env.Library ('memory', [sources])
test_memory = env.Program (['test_Memory.cpp', sources])

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-inc',env.Install ('#/include',includes))
env.Alias('install-lib',env.Install ('#/lib',libraries))
env.Alias('install-bin',env.Install ('#/bin', test_memory))




