Import('env')

components = ['error', 
              'simulation', 
              'data',
              'field',
              'parameters', 
              'parallel', 
              'user', 
              'user-ppm', 
              'method', 
              'monitor',
              'cello' ]

libraries  = ['png','boost_thread-mt']
includes   = [Glob('schedule*hpp')]
sources    = [Glob('schedule*cpp')]

env = env.Clone(LIBS=[components,libraries])

libraries = env.Library ('schedule', [sources])
binaries  = env.Program (['test_Schedule.cpp', sources])

env.Alias('install-inc',env.Install ('#/include',includes))
env.Alias('install-lib',env.Install ('#/lib',libraries))
env.Alias('install-bin',env.Install ('$BINPATH', binaries))







