Import('env')

components = ['error', 'disk', 'memory', 'monitor', 'parallel']
libraries  = ['xlf90','hdf5', 'png']

defines_cpp  = ' -DNO_OPTIMIZE_CELL_WIDTH -Dp8 -Dr8 -DSMALL_INTS -DLINUX'
defines_fortran = ' -WF,-DNO_OPTIMIZE_CELL_WIDTH -WF,-Dp8 -WF,-Dr8 -WF,-DSMALL_INTS -WF,-DLINUX'

env = env.Clone(LIBS = [components,libraries])
env.Append(CCFLAGS = defines_cpp)
env.Append(FORTRAN  = defines_fortran)

# not supported by older scons
# env.SetOption('warn', 'no-fortran-cxx-mix')

sources  = [
	'cello_hydro.cpp',
        Glob('Cosmology*cpp'),
	'data_dump.cpp',
	'image_dump.cpp',
        Glob('Grid_*cpp'),
        Glob('initialize_*cpp'),
	'PPML_Conservative.F',
	'PPML_HLLD.F',
	'PPML_MAIN.F',
	'PPML_monot.F',
	'PPML_potokx.F',
	'PPML_potoky.F',
	'PPML_potokz.F',
	'PPML_Primitive.F',
	'PPML_sub.F',
	'PPML_TimeStep.F',
	'SetExternalBoundary.cpp']

libraries = env.Library ('enzo-ppml', sources)
binaries  = env.Program (['test_ppml.cpp', sources])

env.Alias('install-bin', env.Install ('$BINPATH', binaries))







