Import('env')
Import('parallel_run')
Import('serial_run')
Import('ip_charm')

Import('bin_path')
Import('test_path')

#----------------------------------------------------------
#defines
#----------------------------------------------------------

env['CPIN'] = 'touch parameters.out; mv parameters.out ${TARGET}.in'
env['RMIN'] = 'rm -f parameters.out'
env['clocal_cmd'] = '++local'


date_cmd = 'echo $TARGET > test/STATUS; echo "---------------------"; date +"%Y-%m-%d %H:%M:%S";'

make_movie = Builder(action = "png2swf -r 5 -o $TARGET ${ARGS} ")
png_to_gif = Builder(action = "convert -delay 5 -loop 0 ${ARGS} $TARGET ")

env.Append(BUILDERS = { 'MakeMovie' : make_movie})
env.Append(BUILDERS = { 'pngToGif'  : png_to_gif})




run_adapt = Builder(action = "$RMIN; " + date_cmd + parallel_run + " $SOURCE $clocal_cmd  $ARGS " + " > $TARGET 2>&1; $CPIN; $COPY")
env.Append(BUILDERS = { 'RunAdapt' : run_adapt } )
env_mv_adapt = env.Clone(COPY = 'mkdir -pv ' + test_path + '/AmrPpm/Adapt-L5-P1; mv `ls *.png *.h5` ' + test_path + '/AmrPpm/Adapt-L5-P1')


#-------------------------------------------------------------
#load balancing
#-------------------------------------------------------------
#parallel

balance_adapt = env_mv_adapt.RunAdapt (
     'test_adapt-L5-P1.unit',
     bin_path + '/enzo-e',
     ARGS='input/Adapt/adapt-L5-P1.in')

Clean(balance_adapt,
     [Glob('#/' + test_path + '/Adapt-L5-P1/adapt-L5-P1*.png')])

env.MakeMovie("/Adapt-L5-P1/adapt-L5-P1-mesh.swf", "test_adapt-L5-P1.unit", \
              ARGS = test_path + "/AmrPpm/Adapt-L5-P1/adapt-L5-P1-mesh-*.png");
env.PngToGif("/Adapt-L5-P1/adapt-L5-P1-mesh.gif", "test_adapt-L5-P1.unit", \
              ARGS = test_path + "/AmrPpm/Adapt-L5-P1/adapt-L5-P1-mesh-*.png");

env.MakeMovie("/Adapt-L5-P1/adapt-L5-P1-density.swf", "test_adapt-L5-P1.unit", \
              ARGS = test_path + "/AmrPpm/Adapt-L5-P1/adapt-L5-P1-density-*.png");
env.PngToGif("/Adapt-L5-P1/adapt-L5-P1-density.gif", "test_adapt-L5-P1.unit", \
              ARGS = test_path + "/AmrPpm/Adapt-L5-P1/adapt-L5-P1-density-*.png");


