#------------------------------
# DIRECTORIES
#------------------------------
#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import('parallel_type')

#------------------------------
# DEPENDENCIES
#------------------------------

components = ['method','field', 'parameters', 'error','disk','memory','monitor','parallel','cello','enzo']
libraries  = ['hdf5', 'png', '$FORTRANLIBS']

#------------------------------
# ENVIRONMENTS
#------------------------------

env = env.Clone (LIBS = [components,libraries])

#------------------------------
# SOURCE
#------------------------------

sources  = [Glob('initialize*cpp'),
            Glob('Cosmology*.cpp'),
            Glob('Grid_*cpp'),
            Glob('*.F'),
	   '../image_dump.cpp',
           '../SetExternalBoundary.cpp',
	   'FindField.cpp',
           'sum_field.cpp',
	   '../initialize_hydro.cpp']

#------------------------------
# TARGETS
#------------------------------

binaries = [env.Program (['test_ppm.cpp',      sources])]
libraries = env.Library ('enzo-ppm', sources)

if (parallel_type == "charm"):
	test = 'test_ppm'
	env.CharmBuilder(test + '.decl.h',test + '.ci',ARG = test)
	env.Depends(env.Object(test + '.cpp'),test + '.decl.h')

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-bin', env.Install ('#/bin', binaries))
env.Alias('install-lib',env.Install ('#/lib',    libraries))
