#------------------------------
# DIRECTORIES
#------------------------------
#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import('type')
Import('use_papi')

#------------------------------
# DEPENDENCIES
#------------------------------

components = ['enzo','method','mesh','field','error','disk','memory','parallel','parameters','monitor','cello']

if (use_papi):
	components = components + ['papi','pfm']

components = components + ['hdf5']

libraries  = ['png', '$FORTRANLIBS']

#------------------------------
# ENVIRONMENTS
#------------------------------

env = env.Clone (LIBS = [components,libraries])

#------------------------------
# SOURCE
#------------------------------

sources  = [Glob('initialize*cpp'),
            Glob('Cosmology*.cpp'),
            Glob('Grid_*cpp'),
            Glob('*.F'),
	    'FindField.cpp',
	    'sum_field.cpp']

#------------------------------
# TARGETS
#------------------------------

binaries = [env.Program (['test_ppm.cpp',      sources])]
libraries = env.Library ('enzo-ppm', sources)

if (type == "charm"):
	test = 'test_ppm'
	env.CharmBuilder(test + '.decl.h',test + '.ci',ARG = test)
	env.Depends(env.Object(test + '.cpp'),test + '.decl.h')

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-lib',env.Install ('#/lib',    libraries))
env.Alias('install-bin',env.Install ('#/bin',    binaries))
env.Alias('install-bin',env.Install ('#/bin-'+type,binaries))
