#------------------------------
# DIRECTORIES
#------------------------------
#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import('parallel_type')
Import('use_papi')
Import('use_hdf5')

#------------------------------
# DEPENDENCIES
#------------------------------

components = ['method','field', 'error','disk','memory','monitor','enzo', 'parallel', 'parameters' , 'cello']

if (use_papi):
	components = components + ['papi','pfm']
if (use_hdf5):
	components = components + ['hdf5']

libraries  = ['png', '$FORTRANLIBS']

#------------------------------
# ENVIRONMENTS
#------------------------------

env = env.Clone (LIBS = [components,libraries])

#------------------------------
# SOURCE
#------------------------------

sources  = [Glob('initialize*cpp'),
            Glob('Cosmology*.cpp'),
            Glob('Grid_*cpp'),
            Glob('*.F'),
	   '../image_dump.cpp',
           '../SetExternalBoundary.cpp',
	   'FindField.cpp',
           'sum_field.cpp',
	   '../initialize_hydro.cpp']

#------------------------------
# TARGETS
#------------------------------

binaries = [env.Program (['test_ppm.cpp',      sources])]
libraries = env.Library ('enzo-ppm', sources)

if (parallel_type == "charm"):
	test = 'test_ppm'
	env.CharmBuilder(test + '.decl.h',test + '.ci',ARG = test)
	env.Depends(env.Object(test + '.cpp'),test + '.decl.h')

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-bin', env.Install ('#/bin', binaries))
env.Alias('install-lib',env.Install ('#/lib',    libraries))
