#------------------------------
# DIRECTORIES
#------------------------------
#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import('type')
Import('use_papi')

#------------------------------
# DEPENDENCIES
#------------------------------

components = ['enzo','method','mesh','field','error','disk','memory','parallel','parameters','monitor','cello']

if (use_papi):
	components = components + ['papi','pfm']

components = components + ['hdf5']

libraries  = ['png', '$FORTRANLIBS']

#------------------------------
# ENVIRONMENTS
#------------------------------

env = env.Clone(LIBS = [components,libraries])

#------------------------------
# SOURCE
#------------------------------

includes = ['fortran.h']
sources = [
        Glob('Cosmology*cpp'),
        Glob('Grid_*cpp'),
#        Glob('initialize_*cpp'),
	'PPML_Conservative.F',
	'PPML_HLLD.F',
	'PPML_MAIN.F',
	'PPML_monot.F',
	'PPML_potokx.F',
	'PPML_potoky.F',
	'PPML_potokz.F',
	'PPML_Primitive.F',
	'PPML_sub.F',
	'PPML_TimeStep.F','fortran.h']

#------------------------------
# TARGETS
#------------------------------

libraries = env.Library ('enzo-ppml', sources)

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-lib',env.Install ('#/lib/'+type,libraries))
env.Alias('install-inc',env.Install ('#/include',  includes))









