#------------------------------
# DIRECTORIES
#------------------------------

#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import('type')

#------------------------------
# DEPENDENCIES
#------------------------------

components = ['mesh', 'field',
              'simulation', 'method', 'io',
              'disk','memory','parallel',
              'parameters', 'error',
              'test','cello',
              'monitor','performance' ]

libraries  = ['png','hdf5']

#------------------------------
# SOURCE
#------------------------------

includes = [Glob('io*hpp')]
sources  = [Glob('io*cpp')]

#------------------------------
# ENVIRONMENTS
#------------------------------

env = env.Clone(LIBS=[components,libraries])

#------------------------------
# TARGETS
#------------------------------

libraries = env.Library ('io', [sources])

binaries = [env.Program (['test_ItReduce.cpp'])]

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-inc',env.Install ('#/include',  includes))
env.Alias('install-lib',env.Install ('#/lib/'+type,libraries))
env.Alias('install-bin',env.Install ('#/bin/'+type,binaries))
