#------------------------------
# DIRECTORIES
#------------------------------
#------------------------------
# IMPORTS
#------------------------------
Import('env')
Import('type')
#------------------------------
# DEPENDENCIES
#------------------------------
# components = [ 
#               'mesh','field', 
#               'simulation','method',
#               'disk','memory','parallel',
#               'parameters','monitor',
#               'performance', 'error',
#               'test','cello']
components = ['mesh', 'field',
              'simulation', 'method', 'io',
              'disk','memory','parallel',
              'parameters', 'error',
              'test','cello',
              'monitor','performance' ]

libraries  = ['png','hdf5']

#------------------------------
# ENVIRONMENTS
#------------------------------
env = env.Clone(LIBS=[components,libraries])
#------------------------------
# SOURCE
#------------------------------
includes = [Glob('io*hpp')]
sources  = [Glob('io*cpp')]
#------------------------------
# TARGETS
#------------------------------

libraries = env.Library ('io', [sources])

binaries = [env.Program (['test_ItReduce.cpp'])]

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-inc',env.Install ('#/include',  includes))
env.Alias('install-lib',env.Install ('#/lib/'+type,libraries))
env.Alias('install-bin',env.Install ('#/bin/'+type,binaries))
