#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import('type')

#------------------------------
# DEPENDENCIES
#------------------------------

components = ['method', 
              'mesh', 'field', 
              'memory', 'parallel', 
              'parameters', 'monitor',
              'error',
              'cello']
# libraries  = ['$FORTRANLIBS']
libraries  = []

#------------------------------
# ENVIRONMENTS
#------------------------------
env = env.Clone(LIBS=[components,libraries])
#------------------------------
# SOURCE
#------------------------------
includes = [Glob('method*hpp'), Glob('*.h')]
sources  = [Glob('method*cpp')]
#------------------------------
# TARGETS
#------------------------------
libraries = env.Library ('method', sources)
#------------------------------
# INSTALL
#------------------------------

env.Alias('install-inc',env.Install ('#/include',includes))
env.Alias('install-lib',env.Install ('#/lib/'+type,libraries))








