#------------------------------
# IMPORTS
#------------------------------

Import('env')

#------------------------------
# DEPENDENCIES
#------------------------------

components = ['method', 'data', 'field', 'error','parallel', 'monitor', 'parameters', 'memory', 'cello']
libraries  = ['png', '$FORTRANLIBS']

#------------------------------
# ENVIRONMENTS
#------------------------------
env = env.Clone(LIBS=[components,libraries])
#------------------------------
# SOURCE
#------------------------------
includes = [Glob('method*hpp'), Glob('*.h')]
sources  = [Glob('method*cpp')]
#------------------------------
# TARGETS
#------------------------------
libraries = env.Library ('method', sources)
#------------------------------
# INSTALL
#------------------------------

env.Alias('install-inc',env.Install ('#/include',includes))
env.Alias('install-lib',env.Install ('#/lib',    libraries))








