Import('env')

includes = [Glob('method*hpp')]
sources  = ['method_method.cpp']


env.Alias('install-inc',env.Install ('#/include',includes))

libraries = env.Library ('method', [sources])
env.Alias('install-lib',env.Install ('#/lib',libraries))




