Import('env')

components = ['error','memory']

env = env.Clone(LIBS=[components])

includes = [Glob('performance*hpp')]

env.Alias('install-inc',env.Install ('#/include',includes))

sources  = [Glob('performance*cpp')]

libraries = env.Library ('performance', [sources])

env.Alias('install-lib',env.Install ('#/lib',libraries))

test_performance = env.Program(['test_performance.cpp', sources])
time_matvec      = env.Program(['time_matvec.cpp',      sources])

env.Alias('install-bin', env.Install ('$BINPATH', [test_performance,time_matvec]))




