#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import('type')
Import('use_papi')

#------------------------------
# DEPENDENCIES
#------------------------------


components = ['monitor',
	      'error',
	      'test','cello']

libraries  = ['png']
if (use_papi):
	libraries = libraries + ['papi','pfm']

#------------------------------
# ENVIRONMENTS
#------------------------------

env = env.Clone(LIBS=[components,libraries])

#------------------------------
# SOURCE
#------------------------------

includes = [Glob('performance*hpp')]
sources  = [Glob('performance*cpp')]

#------------------------------
# TARGETS
#------------------------------

libraries        = env.Library ('performance', [sources])

if (type == "charm"):
	sources = sources + ["../main.cpp"]

test_performance = env.Program(['test_Performance.cpp', sources])
test_papi        = env.Program(['test_Papi.cpp',        sources])

binaries = [test_performance,test_papi]

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-inc',env.Install ('#/include',includes))
env.Alias('install-lib',env.Install ('#/lib',    libraries))
env.Alias('install-bin',env.Install ('#/bin',    binaries))
env.Alias('install-bin',env.Install ('#/bin/'+type,binaries))




