Import('env')

includes = [Glob('*hpp')]

env.Alias('install-inc',env.Install ('#/include',includes))

sources  = [Glob('error*cpp')]

libraries = env.Library ('error', [sources])

env.Alias('install-lib',env.Install ('#/lib',libraries))

test_error   = env.Program (['test_error.cpp',  sources])
env.Alias('install-bin', env.Install ('$BINPATH', test_error))




