#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import('type')

#------------------------------
# DEPENDENCIES
#------------------------------
#------------------------------
# ENVIRONMENTS
#------------------------------
#------------------------------
# SOURCE
#------------------------------

includes = [Glob('*hpp')]
sources  = [Glob('error*cpp')]

#------------------------------
# TARGETS
#------------------------------

libraries  = env.Library ('error', [sources])
test_error = env.Program (['test_Error.cpp',  sources])

if (type == "charm"):
	test = 'test_Error'
	env.CharmBuilder(test + '.decl.h',test + '.ci',ARG = test)
	env.Depends(env.Object(test + '.cpp'),test + '.decl.h')

binaries = [test_error]

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-inc',env.Install ('#/include',includes))
env.Alias('install-lib',env.Install ('#/lib',    libraries))
env.Alias('install-bin', env.Install ('#/bin',   binaries))
env.Alias('install-bin',env.Install ('#/bin-'+type,binaries))




