Import('env')
Import('parallel_type')

# Define tests for running cccc

# cccc      = Builder(action = "cccc --outdir=$TARGET `find src -name '*.cpp'`")
# env = Environment(BUILDERS = {'Cccc': cccc})
# env.Cccc("cccc");

SConscript('Enzo/SConscript')

SConscript('Data/SConscript')
SConscript('Disk/SConscript')
SConscript('Distribute/SConscript')
SConscript('Error/SConscript')
SConscript('Field/SConscript')
SConscript('Global/SConscript')
SConscript('Memory/SConscript')
SConscript('Mesh/SConscript')
# SConscript('Method/SConscript')
SConscript('Monitor/SConscript')
SConscript('Parallel/SConscript')
SConscript('Parameters/SConscript')
SConscript('Particle/SConscript')
SConscript('Performance/SConscript')
SConscript('Portal/SConscript')
SConscript('Schedule/SConscript')
SConscript('Simulation/SConscript')
SConscript('Task/SConscript')
SConscript('Test/SConscript')
SConscript('User/SConscript')


components = ['schedule','error','memory','monitor','parameters','simulation','enzo','parallel','enzo-ppm','enzo-ppml','mesh','user','data','field','global','cello']

libraries  = ['png', '$FORTRANLIBS','m']


env = env.Clone(LIBS=[components,libraries])


binaries = env.Program(['cello.cpp'])
if (parallel_type == "charm"):
	test = 'cello'
	env.CharmBuilder(test + '.decl.h',test + '.ci',ARG = test)
	env.Depends(env.Object(test + '.cpp'),test + '.decl.h')


includes = [Glob('cello*hpp'), 'config.def']
sources  = [Glob('cello_*cpp')]

libraries = env.Library ('cello', [sources])

env.Alias('install-lib', env.Install ('#/lib',    libraries))
env.Alias('install-inc', env.Install ('#/include',includes))
env.Alias('install-bin', env.Install ('#/bin', binaries))
