all: \
     class-hierarchy.1 \
     class-level.1 \
     class-grid.1 \
     class-problem.1 \
     class-sphere.1 \
     class-discret.1 \
     class-hypre.1 \
     class-mpi.1 \
     class-point.1 \
     hierarchy.1 \
     grid.1 \
     field.1 \
     level.1

%.1: %.mp
	mpost $*.mp
clean:
	rm -rf *~ *.1 *.log
