
Import('env')

components = ['disk', 'error', 'memory']

libraries  = 'hdf5'

env = env.Clone(LIBS=[components,libraries])

includes = [
	'mesh_node16.hpp',
	'mesh_node2k.hpp',
	'mesh_node3k.hpp',
	'mesh_node4.hpp',
	'mesh_node.hpp',
	'mesh_nodek.hpp',
	'mesh_tree16.hpp',
	'mesh_tree2k.hpp',
	'mesh_tree3k.hpp',
	'mesh_tree4.hpp',
	'mesh_treek.hpp']

env.Alias('install-inc',env.Install ('#/include',includes))

sources  = [Glob('mesh*cpp')]

libraries = env.Library ('mesh', [sources])

env.Alias('install-lib',env.Install ('#/lib',libraries))

test_tree   = env.Program (['test_tree.cpp',   sources])
test_tree_k = env.Program (['test_tree_k.cpp', sources])

binaries = [test_tree, test_tree_k]

env.Alias('install-bin',env.Install ('#/bin', binaries))
env.Alias('install-bin',env.Install ('#/bin-'+type,binaries))

link = Builder(action = Copy("$TARGET","$SOURCE"))
env = Environment(BUILDERS = {'Link': link})
env.Link('image.h','circle2.h')

