Import('env')
Import('serial_run')
Import('parallel_run')
Import('ip_charm')
Import('bin_path')
Import('test_path')


#-----------------------------------------------------------
#defines
#-----------------------------------------------------------


env['CPIN'] = 'touch parameters.out; mv parameters.out ${TARGET}.in'
env['RMIN'] = 'rm -f parameters.out'

date_cmd = 'echo $TARGET > test/STATUS; echo "-------------------"; date +"%Y-%m-%d %H:%M:%S";'

run_monitor = Builder(action = "$RMIN; " + date_cmd + serial_run + " $SOURCE $ARGS > $TARGET 2 >&1; $CPIN; $COPY")
env.Append(BUILDERS = { 'RunMonitor' : run_monitor } )
env_mv_monitor = env.Clone(COPY = 'mkdir -p ' + test_path + '/MonitorComponent/Monitor; mv `ls *.png *.h5` ' + test_path + '/MonitorComponent/Monitor')

#------------------------------------------------------------
# Load Balancing
#------------------------------------------------------------


balance_monitor = env_mv_monitor.RunMonitor(
    'test_Monitor.unit',
     bin_path + '/test_Monitor')