#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import('type')

#------------------------------
# DEPENDENCIES
#------------------------------

components = ['error',
	      'performance',
	      'cello']
testing    = ['parallel']
libraries  = ['png']

#------------------------------
# ENVIRONMENTS
#------------------------------

env        = env.Clone(LIBS=[components,libraries,testing])

#------------------------------
# SOURCE
#------------------------------

includes   = [Glob('monitor*hpp'), Glob('png*h')]
sources    = [Glob('monitor*cpp'), Glob('png*cpp')]

#------------------------------
# TARGETS
#------------------------------

libraries  = env.Library ('monitor', [sources])

if (type == "charm"):
	sources = sources + ["../main.cpp"]

binaries   = env.Program (['test_Monitor.cpp', sources])

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-inc',env.Install ('#/include',includes))
env.Alias('install-lib',env.Install ('#/lib',    libraries))
env.Alias('install-bin',env.Install ('#/bin',    binaries))
env.Alias('install-bin',env.Install ('#/bin-'+type,binaries))





