#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import('type')

#------------------------------
# DEPENDENCIES
#------------------------------

components = ['error', 'cello']
testing    = ['parallel']
libraries  = ['png']

#------------------------------
# ENVIRONMENTS
#------------------------------

env        = env.Clone(LIBS=[components,libraries,testing])

#------------------------------
# SOURCE
#------------------------------

includes   = [Glob('monitor*hpp'), Glob('png*h')]
sources    = [Glob('monitor*cpp'), Glob('png*cpp')]

#------------------------------
# TARGETS
#------------------------------

libraries  = env.Library ('monitor', [sources])
binaries   = env.Program (['test_Monitor.cpp', sources])

if (type == "charm"):
	test = 'test_Monitor'
	env.CharmBuilder(test + '.decl.h',test + '.ci',ARG = test)
	env.Depends(env.Object(test + '.cpp'),test + '.decl.h')

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-inc',env.Install ('#/include',includes))
env.Alias('install-lib',env.Install ('#/lib',    libraries))
env.Alias('install-bin',env.Install ('#/bin',    binaries))
env.Alias('install-bin',env.Install ('#/bin-'+type,binaries))





