Import('env')
Import('parallel_run')
Import('serial_run')
Import('ip_charm')

Import('bin_path')
Import('test_path')

#----------------------------------------------------------
#defines
#----------------------------------------------------------

env['CPIN'] = 'touch parameters.out; mv parameters.out ${TARGET}.in'
env['RMIN'] = 'rm -f parameters.out'

date_cmd = 'echo $TARGET > test/STATUS; echo "---------------------"; date +"%Y-%m-%d %H:%M:%S";'

run_prolong_linear = Builder(action = "$RMIN; " + date_cmd + serial_run + " $SOURCE $ARGS > $TARGET 2>&1; $CPIN; $COPY")
env.Append(BUILDERS = { 'RunProlongLinear' : run_prolong_linear } )
env_mv_prolong_linear = env.Clone(COPY = 'mkdir -p ' + test_path + '/ProlongLinear/ProlongLinear; mv `ls *.png *.h5` ' + test_path + '/ProlongLinear/ProlongLinear')

#-------------------------------------------------------------
#load balancing
#-------------------------------------------------------------


balance_prolong_linear = env_mv_prolong_linear.RunProlongLinear (
     'test_ProlongLinear.unit',
     bin_path + '/test_ProlongLinear')