Import('env')

includes = [Glob('data*hpp')]

env.Alias('install-inc',env.Install ('$CPPPATH',includes))

sources  = [Glob('data*cpp')]

lib_data = env.Library ('data', [sources])
env.Alias('install-lib',env.Install ('$LIBPATH',lib_data))

test_data   = env.Program (['test_data.cpp',   sources])
env.Alias('install-bin', env.Install ('$BINPATH', test_data))






