Import('env')

components = ['field','error']

env = env.Clone(LIBS=[components])

includes = [Glob('data*hpp')]

env.Alias('install-inc',env.Install ('#/include',includes))

sources  = [Glob('data*cpp')]

libraries = env.Library ('data', [sources])

env.Alias('install-lib',env.Install ('#/lib',libraries))

test_data   = env.Program (['test_data.cpp',   sources])
env.Alias('install-bin', env.Install ('$BINPATH', test_data))






