#------------------------------
# IMPORTS
#------------------------------

Import('env')
Import('parallel_type')

#------------------------------
# DEPENDENCIES
#------------------------------

components = ['field','error','cello']

#------------------------------
# ENVIRONMENTS
#------------------------------

env = env.Clone(LIBS=[components])

#------------------------------
# SOURCE
#------------------------------

includes   = [Glob('data*hpp')]
sources    = [Glob('data*cpp')]

#------------------------------
# TARGETS
#------------------------------

libraries = env.Library ('data', [sources])
test_data = env.Program (['test_Data.cpp',   sources])

if ("charm" in parallel_type):
	test = 'test_Data'
	env.CharmBuilder(test + '.decl.h',test + '.ci',ARG = test)
	env.Depends(env.Object(test + '.cpp'),test + '.decl.h')

#------------------------------
# INSTALL
#------------------------------

env.Alias('install-inc',env.Install ('#/include',includes))
env.Alias('install-lib',env.Install ('#/lib',    libraries))
env.Alias('install-bin',env.Install ('#/bin',    test_data))
