Import('env')

SConscript('ppm/SConscript')
SConscript('ppml/SConscript')

env.Library ('user-enzo', 
            ['ppm/libenzo-ppm.a', 
             'ppml/libenzo-ppml.a'])

includes = [Glob('*hpp')]
env.Alias('install-inc',env.Install ('#/include',includes))






