Import('env')

includes   = [Glob('*hpp')]
sources    = ['ppm/libenzo-ppm.a', 'ppml/libenzo-ppml.a']

env.Library ('user-enzo', sources)

env.Alias('install-inc',env.Install ('#/include',includes))

SConscript('ppm/SConscript')
SConscript('ppml/SConscript')
