Import('env')

SConscript('ppm/SConscript')
SConscript('ppml/SConscript')

env.Library ('user-enzo', 
            ['ppm/libenzo-ppm.a', 
             'ppml/libenzo-ppml.a'])

env.Alias('install-inc',env.Install ('$CPPPATH',[Glob('*hpp')]))






